---
elasticsearch:
  hosts:
    el-instance:
      ansible_host: 62.84.112.81
      ansible_ssh_private_key_file: '/home/rimm/.ssh/id_rsa'
kibana:
  hosts:
    ki-instance:
      ansible_host: 62.84.112.202
      ansible_ssh_private_key_file: '/home/rimm/.ssh/id_rsa'
app:
  hosts:
    app-instance:
      ansible_host: 62.84.113.228
      ansible_ssh_private_key_file: '/home/rimm/.ssh/id_rsa'
